name: Intelligent-QA-Assistant

services:
  postgres:
    image: postgres
    container_name: Intelligent-QA-Assistant-postgres
    environment:
      POSTGRES_DB: Intelligent-QA-Assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - Intelligent-QA-Assistant_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  Intelligent-QA-Assistant_postgres_data:
